---
config:
  layout: elk
---
classDiagram
    direction TB
    class MainController
    class ViewNavigator
    class Navbar
    class Table
    class LoginView
    class LoginController
    class RegisterView
    class RegisterController
    class HomeView
    class HomeController
    class NetCreationView
    class NetCreationController
    class ShowAllView
    class ShowAllController
    class ComputationListView
    class ComputationListController
    class NetVisualView
    class NetVisualController
    class NotificationService
    class SessionContext
    class PetriNetViewerPane
    class PetriNetCreationPane
    class Notification
    class User
    class PetriNet
    class EnchantedAlert
    class NotificationFactory
    class ToolBar
    class EditorToolBar
    class ViewToolBar
    class AbstractPetriNetPane

    MainController --> ViewNavigator : gestisce navigazione
    MainController --> Navbar : imposta
    ViewNavigator --> LoginView : naviga a
    ViewNavigator --> HomeView : naviga a
    ViewNavigator --> RegisterView : naviga a
    ViewNavigator --> NetCreationView : naviga a
    ViewNavigator --> ShowAllView : naviga a
    ViewNavigator --> ComputationListView : naviga a
    ViewNavigator --> NetVisualView : naviga a

    LoginView ..> LoginController : genera
    LoginController ..> ViewNavigator : richiede navigazione
    RegisterView ..> RegisterController : genera
    RegisterController ..> ViewNavigator : richiede navigazione
    HomeView ..> HomeController : genera
    HomeController ..> ViewNavigator : richiede navigazione
    NetCreationView ..> NetCreationController : genera
    NetCreationController ..> ViewNavigator : richiede navigazione
    ShowAllView ..> ShowAllController : genera
    ShowAllController ..> ViewNavigator : richiede navigazione
    ComputationListView ..> ComputationListController : genera
    ComputationListController ..> ViewNavigator : richiede navigazione
    NetVisualView ..> NetVisualController : genera
    NetVisualController ..> ViewNavigator : richiede navigazione

    ShowAllController --> Table : usa
    ComputationListController --> Table : usa
    HomeController --> Table : usa
    NetVisualController --> PetriNetViewerPane
    NetCreationController --> PetriNetCreationPane

    LoginController ..> NotificationService : inizializza
    LoginController ..> SessionContext : imposta
    Navbar ..> NotificationService : Logout -> cancella
    Navbar ..> SessionContext : Logout -> cancella
    HomeController --> SessionContext : usa
    HomeController --> NotificationService : usa
    NetCreationController --> PetriNet : usa
    NetVisualController --> PetriNet : usa
    HomeController --> NotificationFactory : serializza
    SessionContext --> User : usa
    HomeController --> EnchantedAlert
    NetCreationController --> EnchantedAlert
    NetVisualController --> EnchantedAlert

    ToolBar <|-- EditorToolBar
    ToolBar <|-- ViewToolBar

%% -- NET CREATION CONTROLLER RELATIONS --
    NetCreationController --> EditorToolBar : crea/usa
    EditorToolBar --> NetCreationController : callback
    NetCreationController --> PetriNetCreationPane : crea/usa
    EditorToolBar --> PetriNetCreationPane : interagisce

%% -- NET VISUAL CONTROLLER RELATIONS --
    NetVisualController --> ViewToolBar : crea/usa
    ViewToolBar --> NetVisualController : callback
    NetVisualController --> PetriNetViewerPane : crea/usa
    ViewToolBar --> PetriNetViewerPane : interagisce

    NotificationService --> Notification : usa
    AbstractPetriNetPane <|-- PetriNetCreationPane
    AbstractPetriNetPane <|-- PetriNetViewerPane