classDiagram

direction TB


%% ======= Relationships =======

%% Main flow

MainController --> ViewNavigator

ViewNavigator --> LogniView

MainController --> NavbarComponent : imposta


%% Auth

LogniView --> LoginController : genera

LoginController --> HomeView

LoginController --> RegisterView

RegisterView --> RegisterController : genera

RegisterController --> LogniView


%% Home navigation

HomeView --> HomeController : genera

HomeController --> NetCreationView

HomeController --> ShowAllView

HomeController --> ComputationListView

HomeController --> NetVisualView


%% Content creation

NetCreationView --> NetCreationController : genera

ShowAllView --> ShowAllController : genera

ComputationListView --> ComputationListController : genera


%% Shared Component usage

ShowAllController --> Table : uses

ComputationListController --> Table : uses

HomeController --> Table : uses


%% Visualization

ShowAllController --> NetVisualView

ComputationListController --> NetVisualView

NetVisualView --> NetVisualController : genera 