classDiagram


    LoginFrame ..|> LoginListener : |use|
    LoginListener --> HomeFrame



    HomeFrame ..|> HomeListener : |use|

    HomeListener --> ShowAllFrame
    HomeListener --> PetriNetFrame


    ShowAllFrame ..|> ShowAllListener : |use|



    NotificationPopUp ..|> NotificationPopUpListener : |use|
    TopbarFrame ..|> TopBarListener : |use|
    TopBarListener --|> NotificationPopUp

    NotificationPopUpListener --> NotificationFrame
    NotificationFrame ..|> NotificationListener : |use|

    ShowAllListener --> PetriNetFrame
    NotificationListener --> PetriNetFrame
    NotificationPopUpListener --> PetriNetFrame