sequenceDiagram
    actor Admin as :Admin
    participant EditorPane as PetriNetEditorPane
    participant Popup as PopupMenu
    participant Builder as PetriNetBuilder
    participant GraphView as SmartGraphPanel
    participant EditorPane as PetriNetEditorPane
    participant Builder as PetriNetBuilder

    participant GraphView as SmartGraphPanel

    Admin->>EditorPane: onSingleSingleClickAction(point)


