sequenceDiagram
    actor Admin as :Admin
    participant Popup as alert : EnhancedAlert
    participant GraphView as graph : SmartGraphPanel
    participant EditorPane as editorPane : PetriNetEditorPane
    participant Builder as builder : PetriNetBuilder


    Admin->>EditorPane: onCanvasSingleClickAction(point)
    activate EditorPane
    loop nome non valido
        EditorPane->>+Popup: new EnhancedAlert()
        Popup-->>-EditorPane: nodeLabel
        break nome valido
            EditorPane->>EditorPane: nodeLabel
        end
        break cancel
            EditorPane-->>Admin: return
        end
    end

        alt Tipologia = Place
            EditorPane->>Builder: newPlace(nodeLabel)
            Builder-->>EditorPane: PetriNetBuilder

        else Tipologia = Transition
        EditorPane->>Builder: newTransition(nodeLabel)
        Builder-->>EditorPane: PetriNetBuilder
        end

        EditorPane->>+GraphView: insertVertex(newNode, position)
        GraphView-->>-EditorPane: newVertex

    deactivate EditorPane
