sequenceDiagram
    actor Persona as :Perona
    participant Controller as controller : NetVisualController


    Persona->>Controller:viewPetriNet
    create participant Pane as viewerPane : PetriNetViewerPane
    Controller->>Pane: new(netName, computation)
    Pane->>+Pane: onGraphInitialized
    create participant Parser as parser : PNMLParser
    Pane->>+Parser: parse(netName)
    create participant Model as model : PetriNetModel
    Parser->>Model: create

    Parser-->>-Pane: PetriNetModel
    Pane->>Pane: addNodes()
    Pane->>Pane: addConnections()

    Pane->>Pane: computeAndApplyFirableTransitions
    deactivate Pane
